# Header

menu:
  随笔: https://top.zshipu.com/
  CSDN: https://top.zshipu.com/topcsdn
  Segmentfault: https://top.zshipu.com/topSegmentfault
  掘金: https://top.zshipu.com/topjuejin
  开源中国: https://top.zshipu.com/topopencn
  Linux中国: https://top.zshipu.com/toplinuxcn
  Go语言中文网: https://top.zshipu.com/topgoforum

# SubNav
subnav:
  github: "https://github.com/liliang8858"
  #weibo: "https://weibo.com/512316815"
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/edwin-ed"
  #qq: "#"
  #weixin: "#"
  jianshu: "https://www.jianshu.com/u/ab131421cc9e"
  #douban: "#"
  segmentfault: "https://segmentfault.com/u/hupan"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:sblig@126.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: http://home.zshipu.com/res%2Fimg%2Falipay.jpg
# 微信二维码图片地址
weixin: http://home.zshipu.com/res%2Fimg%2Fweixin.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar:

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: liliang8858      #你的 GitHub ID
gitment_repo: 'zspblogcomment'          #存储评论的 repo
gitment_oauth:
  client_id: 'ec3adfa1a072fdaa4d91'           #client ID
  client_secret: '7a84a35d6d8bce205398c3d5d7f6ee1ce8e1ab53'       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  友情链接1: https://blog.zshipu.com/
  友情链接2: https://blog.zshipu.com/read/
  友情链接3: https://blog.zshipu.com/note/
  友情链接4: https://blog.zshipu.com/tlg/
  友情链接5: https://blog.zshipu.com/media/
  友情链接6: https://blog.zshipu.com/article/post/

aboutme: 很惭愧<br><br>只做了一点微小的工作<br>谢谢大家

article_txt: 免责声明：本页面内容均来源于站内编辑发布，部分信息来源互联网，并不意味着本站赞同其观点或者证实其内容的真实性，如涉及版权等问题，请立即联系客服进行更改或删除，保证您的合法权益。转载请注明来源，欢迎对文章中的引用来源进行考证，欢迎指出任何有错误或不够清晰的表达。也可以邮件至 sblig@126.com

bottom_text: 浙 ICP 备19032823号-1
